import type { NextPage } from 'next';
import { Layout } from '../components/Layout';
import Head from 'next/head';
import Like from '../components/atom/icon/Like';
import Person from '../components/atom/icon/Person';
import Next from '../components/atom/button/Next';
import Atom from '../components/Atom';
import FormSearch from '../components/atom/FormSearch';


const Home: NextPage = () => {
  return (
    <Layout>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
      </Head> 
      <div className='flex flex-col gap-28 items-center my-20'>
          <Like/>     
          <Person/>
          <Next/>
          <Atom/>         
          <FormSearch/>
      </div>
    </Layout>
  );
};

export default Home;